function saveann(opt,ann)
  %saveann Summary of this function goes here
  %   Detailed explanation goes here

  opt_str = [opt.m.name '_' ...
             opt.m.ann '_' ...
             mat2str(cell2mat(opt.m.level)) '_' ...
             mat2str(cell2mat(opt.m.erode1)) '_' ...
             mat2str(cell2mat(opt.m.erode2)) '_' ...
             cell2mat(opt.m.warp) '_' ...
             cell2mat(opt.m.interp) '_' ...
             cell2mat(opt.m.smoother) '_' ...  
             mat2str(cell2mat(opt.m.sigma)) '_' ...
             cell2mat(opt.m.shape_model) '_' ...
             cell2mat(opt.m.tex_model) '_' ...
             mat2str(cell2mat(opt.m.alpha))];
          
  hash_code = DataHash(opt.reg_exp_query);
  file_name = [opt_str '_' hash_code '.mat'];
  
  save([opt.ann_root file_name],'ann','-v7.3');

end