parfor i = 1:n_fittings

  j = floor((i-1)/n_rand) + 1;

  % read image from input file
  img=imread([path data(j).name]);
  ori = annread([path data(j).name(1:strfind(data(j).name,'.')) test_db.ann_type],68);

  [fit,ini,~] = f.FitSparse(img,ori);
  fann(:,:,i) = fit(:,:,end);
  iann(:,:,i) = ini;
  oann(:,:,i) = ori;

  if opt.verbose
    if all(all(fit(:,:,end)))
      [rms_err,p2p_err,ram_err,hel_err] = computeerr(fit(:,:,end), ...
        ori, ...
        ori, ...
        test_db.comp);
      fprintf(['  - img: ' int2str(j) '/' int2str(test_db.n_data) ...
        '\t\t  rms_err: ' num2str(rms_err) ...
        '\t  p2p_err: ' num2str(p2p_err) ...
        '\t  ram_err: ' num2str(ram_err) ...
        '\t  hel_err: ' num2str(hel_err) ...
        '\n']);
    else
      fprintf([' - image: ' int2str(j) '/' int2str(test_db.n_data) ...
        '\t face not detected!' ...
        '\n']);
    end
  end
  
end